publicHoistPattern:
  - "@primevue/core"

allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  unrs-resolver: true

catalog:
  "@types/node": "24" # to avoid updating it in package.json when updating pkgs

patchedDependencies:
  vue-i18n: patches/vue-i18n.patch

minimumReleaseAgeExclude:
  - prettier@3.9.1
